version: '3.8'

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./.init/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  product-management:
    build:
      context: .                # el build context es la carpeta product/
      dockerfile: ./.init/docker/Dockerfile
      args:
        MODULE: product-management
    ports:
      - "8081:8080"                      # host 8081 → contenedor 8080
    depends_on:
      - db
      - redis

  account-management:
    build:
      context: ./account-management                 # contexto = carpeta account/
      dockerfile: ../.init/docker/Dockerfile
    ports:
      - "8082:8080"                      # host 8082 → contenedor 8080
    depends_on:
      - db
      - redis

  payment-management:
    build:
      context: ./payment-management                 # contexto = carpeta payment/
      dockerfile: ../.init/docker/Dockerfile
    ports:
      - "8083:8080"                      # host 8083 → contenedor 8080
    depends_on:
      - redis

  order-management:
    build:
      context: ./order-management                   # contexto = carpeta order/
      dockerfile: ../.init/docker/Dockerfile
    ports:
      - "8084:8080"                      # host 8084 → contenedor 8080
    depends_on:
      - db
      - redis

volumes:
  db_data: