version: '3.8'

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./.init/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  product-management:
    build:
      context: .
      dockerfile: ./.init/docker/Dockerfile
      args:
        MODULE: product-management
    environment:
      DB_HOST: db
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis

  account-management:
    build:
      context: .
      dockerfile: ./.init/docker/Dockerfile
      args:
        MODULE: account-management
    environment:
      DB_HOST: db
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - db
      - redis

  payment-management:
    build:
      context: .
      dockerfile: ./.init/docker/Dockerfile
      args:
        MODULE: payment-management
    environment:
      DB_HOST: db
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      - redis

  order-management:
    build:
      context: .
      dockerfile: ./.init/docker/Dockerfile
      args:
        MODULE: order-management
    environment:
      DB_HOST: db
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    depends_on:
      - db
      - redis

  ecom-gateway:
    build:
      context: ../ecom-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - product-management
      - account-management
      - payment-management
      - order-management
    environment:
      ACCOUNT_HOST: account-management
      PRODUCT_HOST: product-management
      PAYMENT_HOST: payment-management
      ORDER_HOST: order-management
      SERVER_PORT: 8080

volumes:
  db_data: