spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cart:
  url: http://${GATEWAY_HOST:localhost}:8080/api/v1/cart

server:
  port: ${SERVER_PORT:8084}