spring:
  application:
    name: product-management
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  open-api:
    info:
      title: "API de Gestión de Productos"
      description: "Esta API permite crear, leer, actualizar y borrar productos en el sistema"
      version: "1.0.0"

server:
  port: ${SERVER_PORT:8081}
