spring:
  application:
    name: account-management
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  open-api:
    info:
      title: "API de Gestión de Usuarios"
      description: "Esta API permite crear, registrar y autenticar usuarios en el sistema"
      version: "1.0.0"


server:
  port: ${SERVER_PORT:8082}