spring:
  application:
    name: account-management
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  open-api:
    info:
      title: "API de Gestión de Usuarios"
      description: "Esta API permite crear, registrar y autenticar usuarios en el sistema"
      version: "1.0.0"